# Generated by Django 3.1.1 on 2020-10-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingContry',
            new_name='billingCountry',
        ),
    ]
